services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: wordpress_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    volumes:
      - wordpress_db:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - wordpress_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # WordPress Application
  wordpress:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: wordpress_app
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    environment:
      # WordPress Database Configuration
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_CHARSET: utf8mb4
      WORDPRESS_DB_COLLATE: utf8mb4_unicode_ci
      
      # WordPress Configuration
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', '${SITE_URL}');
        define('WP_SITEURL', '${SITE_URL}');
        define('FORCE_SSL_ADMIN', ${FORCE_SSL:-false});
        define('WP_DEBUG', ${WP_DEBUG:-false});
        define('WP_DEBUG_LOG', ${WP_DEBUG_LOG:-false});
        define('WP_DEBUG_DISPLAY', ${WP_DEBUG_DISPLAY:-false});
        define('SCRIPT_DEBUG', ${SCRIPT_DEBUG:-false});
        define('WP_MEMORY_LIMIT', '${WP_MEMORY_LIMIT:-256M}');
        define('WP_MAX_MEMORY_LIMIT', '${WP_MAX_MEMORY_LIMIT:-512M}');
        define('AUTOMATIC_UPDATER_DISABLED', ${AUTO_UPDATE_DISABLED:-true});
        define('WP_AUTO_UPDATE_CORE', ${WP_AUTO_UPDATE_CORE:-false});
        define('DISALLOW_FILE_EDIT', ${DISALLOW_FILE_EDIT:-true});
        define('DISALLOW_FILE_MODS', ${DISALLOW_FILE_MODS:-false});
      
      # Apache Configuration
      DOMAIN_NAME: ${DOMAIN_NAME}
      
      # Custom Quiz App Environment
      QUIZ_DB_HOST: db:3306
      QUIZ_DB_NAME: ${MYSQL_DATABASE}
      QUIZ_DB_USER: ${MYSQL_USER}
      QUIZ_DB_PASSWORD: ${MYSQL_PASSWORD}
      QUIZ_UPLOAD_PATH: /var/www/html/uploads
      QUIZ_MAX_FILE_SIZE: ${QUIZ_MAX_FILE_SIZE:-10M}
      
    volumes:
      - wordpress_data:/var/www/html
      - ./uploads:/var/www/html/uploads
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wordpress_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy (Optional for SSL termination)
  nginx:
    image: nginx:alpine
    container_name: wordpress_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/ssl:/etc/nginx/ssl:ro
    depends_on:
      - wordpress
    networks:
      - wordpress_network
    profiles:
      - nginx

  # phpMyAdmin (only for development/staging)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wordpress_phpmyadmin
    restart: unless-stopped
    ports:
      - "${PMA_PORT:-8080}:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_ARBITRARY: 1
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wordpress_network
    profiles:
      - development

networks:
  wordpress_network:
    driver: bridge

volumes:
  wordpress_db:
    driver: local
  wordpress_data:
    driver: local
