name: Deploy via SFTP/SSH

on:
  push:
    branches: [ main, production ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Deploy to server via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.SSH_USERNAME }}
        server: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        local_path: './'
        remote_path: ${{ secrets.REMOTE_PATH }}
        sftp_only: true
        exclude: |
          .git/
          .github/
          node_modules/
          wp-config.php
          wp-content/uploads/
          wp-content/cache/
          *.sql
          *.log
          .env